// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6TPvavIhQLMv-r_9pu1JeW6A91OuW4pc',
    appId: '1:564794911801:web:0dd094df573729e385f1e8',
    messagingSenderId: '564794911801',
    projectId: 'chat-72017',
    authDomain: 'chat-72017.firebaseapp.com',
    storageBucket: 'chat-72017.firebasestorage.app',
    measurementId: 'G-TL1B18GCL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDch0688he9vhFwt0HpGL-O59C9lj47QQY',
    appId: '1:564794911801:android:6d9c61da7fd15fef85f1e8',
    messagingSenderId: '564794911801',
    projectId: 'chat-72017',
    storageBucket: 'chat-72017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaiZlVIbvAq5c2GKVyapRU6XRjN7xEV1U',
    appId: '1:564794911801:ios:6e7d3022b0be569985f1e8',
    messagingSenderId: '564794911801',
    projectId: 'chat-72017',
    storageBucket: 'chat-72017.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaiZlVIbvAq5c2GKVyapRU6XRjN7xEV1U',
    appId: '1:564794911801:ios:6e7d3022b0be569985f1e8',
    messagingSenderId: '564794911801',
    projectId: 'chat-72017',
    storageBucket: 'chat-72017.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6TPvavIhQLMv-r_9pu1JeW6A91OuW4pc',
    appId: '1:564794911801:web:d8f0dc8828fbe60e85f1e8',
    messagingSenderId: '564794911801',
    projectId: 'chat-72017',
    authDomain: 'chat-72017.firebaseapp.com',
    storageBucket: 'chat-72017.firebasestorage.app',
    measurementId: 'G-T74FGCGVGB',
  );
}
